version: 0.0.{build}
os: Visual Studio 2017
configuration: Release
environment:
  clone_folder: c:\doog
  COVERALLS_REPO_TOKEN:
    secure: yvqm3RvF03eBaks4yC+CSWM+tiRIAYkipdAxU5pDmKbGUGUGH9EnuPdUnIsRQAu0

before_build:
- cmd: dotnet --version
- cmd: dotnet restore src

build_script:
- cmd: dotnet build src -c release

after_build:
- cmd: 7z a Doog-bin.zip -r src\Doog\bin\**\*.dll
- cmd: 7z a Doog-Samples-bin.zip -r src\Doog\Samples\Doog.Samples\bin\**\*.dll
- cmd: 7z a Snake-bin.zip -r src\Doog\Samples\Snake\bin\**\*.dll

test_script:
- cmd: dotnet test src

artifacts:
  - path: Doog-bin.zip
    name: Doog-bin
  - path: Doog-Samples-bin.zip
    name: Doog-Samples-bin
  - path: Snake-bin.zip
    name: Snake-bin
