version: 0.0.{build}
os: Visual Studio 2015
configuration: Release
environment:
  clone_folder: c:\doog
  COVERALLS_REPO_TOKEN:
    secure: yvqm3RvF03eBaks4yC+CSWM+tiRIAYkipdAxU5pDmKbGUGUGH9EnuPdUnIsRQAu0

before_build:
- cmd: dotnet --version
- cmd: dotnet restore src

build_script:
# The default build
- cmd: dotnet build src -c release

after_build:
- cmd: 7z a Doog-bin.zip -r .\build

test_script:
- cmd: dotnet clean src/Doog.Framework.UnitTests
- cmd: dotnet test src/Doog.Framework.UnitTests -f netcoreapp2.0

artifacts:
  - path: Doog-bin.zip
    name: Doog-bin
